import type { RoleConfig, QuizQuestion, TimelineEvent, Staff } from "@/types";

export const ROLE_CONFIGS: RoleConfig[] = [
  {
    id: "entrance",
    label: "입장통제",
    icon: "🚧",
    color: "text-red-400",
    bgColor: "bg-red-500/10 border-red-500/30",
    description: "게이트 관리·티켓 확인·인원 통제",
    zone: "A구역 메인게이트",
  },
  {
    id: "fnb",
    label: "FOOD",
    icon: "🍺",
    color: "text-amber-400",
    bgColor: "bg-amber-500/10 border-amber-500/30",
    description: "음식·음료 서빙·재고 관리",
    zone: "B구역 푸드코트",
  },
  {
    id: "market",
    label: "플리마켓",
    icon: "🛍️",
    color: "text-green-400",
    bgColor: "bg-green-500/10 border-green-500/30",
    description: "플리마켓 부스 운영·판매 지원",
    zone: "C구역 마켓광장",
  },
  {
    id: "popup",
    label: "팝업",
    icon: "🎪",
    color: "text-purple-400",
    bgColor: "bg-purple-500/10 border-purple-500/30",
    description: "팝업스토어 운영·브랜드 지원",
    zone: "D구역 팝업존",
  },
  {
    id: "stage",
    label: "체험/콘텐츠",
    icon: "🎵",
    color: "text-blue-400",
    bgColor: "bg-blue-500/10 border-blue-500/30",
    description: "공연 진행·관객 안내·무대 안전",
    zone: "E구역 메인스테이지",
  },
  {
    id: "facility",
    label: "편의시설",
    icon: "🏥",
    color: "text-cyan-400",
    bgColor: "bg-cyan-500/10 border-cyan-500/30",
    description: "화장실·의무실·안내센터 운영",
    zone: "F구역 편의시설",
  },
];

export const QUIZ_QUESTIONS: Record<string, QuizQuestion[]> = {
  entrance: [
    {
      id: 1,
      type: "ox",
      question: "입장 티켓 QR코드가 이미 스캔된 경우 재입장을 허용해야 한다.",
      answer: false,
      explanation: "이미 스캔된 QR은 재사용 불가. 재입장 필요시 재입장 스탬프 확인 후 허용하세요.",
    },
    {
      id: 2,
      type: "multiple",
      question: "관람객이 입장 거부에 강하게 항의할 때 올바른 대처 방법은?",
      options: ["즉시 경비팀에 연락한다", "혼자 설득을 계속 시도한다", "무시하고 다음 관람객을 응대한다", "임의로 입장시켜 준다"],
      answer: "즉시 경비팀에 연락한다",
      explanation: "단독 대응은 위험할 수 있습니다. 무전기로 경비팀(#101)에 즉시 연락하세요.",
    },
    {
      id: 3,
      type: "ox",
      question: "음주 상태가 의심되는 관람객은 입장을 거부할 수 있다.",
      answer: true,
      explanation: "안전을 위해 명백히 음주 상태인 관람객의 입장을 거부할 수 있습니다.",
    },
    {
      id: 4,
      type: "multiple",
      question: "화재 경보 발생 시 입장 게이트 스태프의 즉각 조치는?",
      options: ["게이트를 모두 열고 대피 유도", "게이트를 잠그고 대기", "본부에 먼저 보고 후 대기", "개인 대피 먼저 실시"],
      answer: "게이트를 모두 열고 대피 유도",
      explanation: "화재 시 게이트를 개방하여 신속한 대피로를 확보하고 관람객을 지정 대피장소로 안내합니다.",
    },
    {
      id: 5,
      type: "ox",
      question: "만 12세 미만 아동이 보호자 없이 입장을 요청하면 입장시킬 수 있다.",
      answer: false,
      explanation: "미성년자 단독 입장 불가. 보호자 동반 또는 보호자 확인 후 입장 처리하세요.",
    },
    {
      id: 6,
      type: "multiple",
      question: "의심스러운 가방·물품 발견 시 올바른 대처는?",
      options: ["보안팀에 즉시 신고", "직접 가방을 열어 확인", "무시하고 계속 근무", "주변 관람객에게 알림"],
      answer: "보안팀에 즉시 신고",
      explanation: "의심 물품은 절대 직접 만지지 말고 보안팀(#102)에 즉시 신고하세요.",
    },
    {
      id: 7,
      type: "ox",
      question: "수용인원 초과 시 본부 허가 없이 일시적으로 더 입장시킬 수 있다.",
      answer: false,
      explanation: "수용인원 초과는 안전사고 위험. 반드시 운영본부(#100) 지시에 따라 입장 통제하세요.",
    },
  ],
  fnb: [
    {
      id: 1,
      type: "ox",
      question: "음식 서빙 전 반드시 손을 씻거나 위생장갑을 착용해야 한다.",
      answer: true,
      explanation: "식품위생법에 따라 음식 취급 시 항상 위생 조치를 철저히 준수하세요.",
    },
    {
      id: 2,
      type: "multiple",
      question: "관람객이 음식에서 이물질을 발견했다고 신고할 때 대처 방법은?",
      options: ["즉시 사과하고 교환·환불 처리 후 팀장 보고", "관람객의 말을 믿지 않는다", "무시하고 다음 손님을 응대한다", "본인이 임의로 처리한다"],
      answer: "즉시 사과하고 교환·환불 처리 후 팀장 보고",
      explanation: "진심 어린 사과와 신속한 교환·환불이 우선입니다. 반드시 팀장에게 보고하세요.",
    },
    {
      id: 3,
      type: "ox",
      question: "알레르기 정보를 문의하는 관람객에게 '잘 모른다'고 답해도 된다.",
      answer: false,
      explanation: "알레르기는 생명과 직결됩니다. 팀장 또는 취급 메뉴 안내서를 통해 정확한 정보를 제공하세요.",
    },
    {
      id: 4,
      type: "multiple",
      question: "냉장 식품의 관리 온도 기준은?",
      options: ["5°C 이하", "10°C 이하", "15°C 이하", "20°C 이하"],
      answer: "5°C 이하",
      explanation: "냉장 식품은 5°C 이하에서 보관해야 세균 증식을 억제할 수 있습니다.",
    },
    {
      id: 5,
      type: "ox",
      question: "현금 잔돈이 부족하면 관람객에게 카드 결제만 유도해도 된다.",
      answer: false,
      explanation: "현금 부족 시 즉시 팀장에게 보고하여 정산 지원을 요청하세요. 일방적 강요는 불가합니다.",
    },
    {
      id: 6,
      type: "multiple",
      question: "관람객이 음주 상태에서 추가 주류를 요청할 때 대응은?",
      options: ["정중히 거부하고 팀장에게 보고", "요청대로 제공한다", "무시한다", "경찰을 즉시 호출한다"],
      answer: "정중히 거부하고 팀장에게 보고",
      explanation: "과도한 음주는 안전사고 위험입니다. 정중히 거부 후 팀장에게 상황을 보고하세요.",
    },
    {
      id: 7,
      type: "ox",
      question: "가스 누출이 의심될 때 즉시 시설팀에 신고하고 해당 구역 운영을 중단해야 한다.",
      answer: true,
      explanation: "가스 누출은 폭발·화재 위험이 있습니다. 즉시 운영 중단 후 시설팀(#103)에 신고하세요.",
    },
  ],
  market: [
    {
      id: 1, type: "ox",
      question: "마켓 부스의 진열 상품은 허가된 품목만 판매 가능하다.",
      answer: true,
      explanation: "사전 승인된 품목 외 판매는 계약 위반입니다. 문의 시 운영팀(#104)에 확인하세요.",
    },
    {
      id: 2, type: "multiple",
      question: "마켓 구역에서 화재 발생 시 우선 조치는?",
      options: ["소화기 사용 시도 후 대피 유도", "모든 상품 챙기기", "혼자 진화 시도", "그냥 대피"],
      answer: "소화기 사용 시도 후 대피 유도",
      explanation: "초기 소화기로 진화를 시도하되 번지면 즉시 대피 유도. 119 신고는 필수입니다.",
    },
    {
      id: 3, type: "ox",
      question: "부스 운영 시간 외에는 현금 및 귀중품을 부스에 보관해도 된다.",
      answer: false,
      explanation: "운영 시간 외 현금·귀중품은 반드시 지정 금고 또는 운영본부에 보관하세요.",
    },
    {
      id: 4, type: "multiple",
      question: "관람객이 구매 상품에 대한 환불을 요구할 때?",
      options: ["환불 정책 안내 후 팀장 승인 절차 진행", "무조건 거부", "임의로 환불 처리", "무시"],
      answer: "환불 정책 안내 후 팀장 승인 절차 진행",
      explanation: "환불은 사전 공지된 정책에 따라 팀장 승인 후 처리합니다.",
    },
    {
      id: 5, type: "ox",
      question: "부스 앞 통로가 막히도록 상품을 진열해도 된다.",
      answer: false,
      explanation: "통로 막힘은 비상 대피에 지장을 줍니다. 지정된 진열 구역 내에서만 운영하세요.",
    },
    {
      id: 6, type: "multiple",
      question: "도난 사고 발생 시 올바른 대처는?",
      options: ["보안팀 신고 후 목격자 확보", "직접 용의자를 추격", "신고 없이 자체 해결", "그냥 넘어간다"],
      answer: "보안팀 신고 후 목격자 확보",
      explanation: "직접 추격은 위험합니다. 보안팀(#102)에 즉시 신고하고 목격자를 확보하세요.",
    },
    {
      id: 7, type: "ox",
      question: "악천후 시 운영 중단 결정은 스태프 개인이 판단해서 내린다.",
      answer: false,
      explanation: "악천후 운영 중단은 반드시 운영본부(#100) 지시를 따르세요.",
    },
  ],
  popup: [
    {
      id: 1, type: "ox",
      question: "팝업스토어 브랜드 담당자의 지시는 운영본부 지침보다 우선한다.",
      answer: false,
      explanation: "행사 운영 지침은 운영본부가 최우선입니다. 브랜드 요청은 운영팀과 조율하세요.",
    },
    {
      id: 2, type: "multiple",
      question: "팝업존 방문객이 급증하여 혼잡해질 때 대처는?",
      options: ["입장통제팀에 지원 요청", "혼자 통제 시도", "구역 문을 닫는다", "무시"],
      answer: "입장통제팀에 지원 요청",
      explanation: "혼잡 시 입장통제팀(#105)에 즉시 지원을 요청하세요.",
    },
    {
      id: 3, type: "ox",
      question: "브랜드 홍보 촬영을 위한 관람객 동의 없는 촬영을 허용해도 된다.",
      answer: false,
      explanation: "초상권 침해 방지를 위해 관람객 촬영 시 반드시 동의를 구해야 합니다.",
    },
    {
      id: 4, type: "multiple",
      question: "팝업 부스 전기 장비에서 불꽃이 튈 때 즉시 해야 할 일은?",
      options: ["전원 차단 후 시설팀 신고", "그냥 놔둔다", "물을 붓는다", "계속 운영"],
      answer: "전원 차단 후 시설팀 신고",
      explanation: "전기 화재 위험이 있습니다. 즉시 전원을 차단하고 시설팀(#103)에 신고하세요.",
    },
    {
      id: 5, type: "ox",
      question: "미성년자에게 성인 전용 제품(주류·담배)을 판매해도 된다.",
      answer: false,
      explanation: "성인 인증이 불가한 경우 성인 전용 제품 판매는 법적으로 금지됩니다.",
    },
    {
      id: 6, type: "multiple",
      question: "관람객이 촬영 금지 구역에서 촬영을 시도할 때?",
      options: ["정중히 안내하고 촬영 중단 요청", "강제로 기기를 빼앗는다", "무시", "경찰 즉시 호출"],
      answer: "정중히 안내하고 촬영 중단 요청",
      explanation: "강압적 대응은 금지. 정중한 안내 후 거부 시 보안팀에 지원을 요청하세요.",
    },
    {
      id: 7, type: "ox",
      question: "팝업 체험 대기열이 길어질 경우 스태프가 임의로 대기 시간을 단축해도 된다.",
      answer: false,
      explanation: "대기 시간 조정은 브랜드 담당자 및 운영팀과 협의 후 결정해야 합니다.",
    },
  ],
  stage: [
    {
      id: 1, type: "ox",
      question: "공연 중 무대 앞 모쉬핏 구역에서 관람객이 쓰러지면 공연을 즉시 중단시킨다.",
      answer: true,
      explanation: "인명 안전이 최우선입니다. 즉각 공연 중단 후 의료팀(#106)을 호출하세요.",
    },
    {
      id: 2, type: "multiple",
      question: "관람객이 무단으로 무대에 오르려 할 때 대처는?",
      options: ["즉시 제지하고 보안팀 호출", "그냥 둔다", "소리를 지른다", "무대 위로 밀어올린다"],
      answer: "즉시 제지하고 보안팀 호출",
      explanation: "무단 무대 진입은 안전사고 위험. 즉시 제지하고 보안팀(#102)에 지원 요청하세요.",
    },
    {
      id: 3, type: "ox",
      question: "공연 소음이 주변 민원을 유발할 경우 스태프가 임의로 볼륨을 조절한다.",
      answer: false,
      explanation: "음향 조절은 반드시 무대 기술팀과 운영본부 지시에 따라 진행합니다.",
    },
    {
      id: 4, type: "multiple",
      question: "공연 중 조명 장비 오작동 발견 시 즉각 조치는?",
      options: ["기술팀에 즉시 연락", "직접 수리 시도", "공연 계속 진행", "무시"],
      answer: "기술팀에 즉시 연락",
      explanation: "조명 장비 오작동은 낙하 사고 위험이 있습니다. 기술팀(#107)에 즉시 연락하세요.",
    },
    {
      id: 5, type: "ox",
      question: "촬영 금지 공연의 경우 스마트폰 촬영 관람객을 제지해야 한다.",
      answer: true,
      explanation: "아티스트 요청 및 저작권 보호를 위해 정중히 촬영 중단을 안내하세요.",
    },
    {
      id: 6, type: "multiple",
      question: "공연 중 대규모 혼잡·압사 위험 징후 발견 시?",
      options: ["즉시 무대 진행팀에 보고·공연 중단 요청", "혼자 통제 시도", "관람객에게 소리침", "무시"],
      answer: "즉시 무대 진행팀에 보고·공연 중단 요청",
      explanation: "압사 사고는 돌이킬 수 없습니다. 즉시 무대 진행팀과 운영본부에 보고하세요.",
    },
    {
      id: 7, type: "ox",
      question: "폭죽·레이저 등 특수효과 장비는 사전 승인 없이 사용할 수 없다.",
      answer: true,
      explanation: "특수효과는 반드시 기술팀 및 운영본부 사전 승인 후 정해진 순서에만 사용합니다.",
    },
  ],
  facility: [
    {
      id: 1, type: "ox",
      question: "의무실에서는 처방전 없이 전문 의약품을 관람객에게 제공해도 된다.",
      answer: false,
      explanation: "전문 의약품은 의료진만 처방 가능합니다. 일반 응급처치 물품만 제공하세요.",
    },
    {
      id: 2, type: "multiple",
      question: "관람객이 응급 상황(심정지 의심)에 처했을 때 올바른 순서는?",
      options: ["119 신고 → AED 요청 → 심폐소생술 시작", "관람객 방치", "구경꾼 정리 후 신고", "팀장에게만 보고"],
      answer: "119 신고 → AED 요청 → 심폐소생술 시작",
      explanation: "골든타임이 중요합니다. 119 신고와 동시에 AED를 요청하고 즉시 CPR을 시작하세요.",
    },
    {
      id: 3, type: "ox",
      question: "화장실 청소 중 미끄럼 주의 안내판을 반드시 설치해야 한다.",
      answer: true,
      explanation: "안전사고 예방을 위해 청소 중 미끄럼 주의 안내판 설치는 필수입니다.",
    },
    {
      id: 4, type: "multiple",
      question: "분실물 센터에서 습득 물품 처리 방법은?",
      options: ["분실물 대장 기록 후 지정 보관함 보관", "직접 관람객에게 돌려줌", "그냥 두기", "폐기"],
      answer: "분실물 대장 기록 후 지정 보관함 보관",
      explanation: "모든 습득 물품은 분실물 대장에 기록 후 지정 보관함에 보관하세요.",
    },
    {
      id: 5, type: "ox",
      question: "안내센터 스태프는 행사장 모든 구역의 위치 정보를 숙지해야 한다.",
      answer: true,
      explanation: "관람객 안내를 위해 행사장 전체 구역 배치를 미리 숙지하는 것이 필수입니다.",
    },
    {
      id: 6, type: "multiple",
      question: "시설 파손 발견 시 즉각 조치는?",
      options: ["위험 구역 접근 차단 후 시설팀 신고", "직접 수리", "무시", "관람객에게 알림"],
      answer: "위험 구역 접근 차단 후 시설팀 신고",
      explanation: "추가 사고 방지를 위해 접근 차단 후 시설팀(#103)에 즉시 신고하세요.",
    },
    {
      id: 7, type: "ox",
      question: "미아 발생 시 아동을 안내센터로 데려와 방송 안내를 요청해야 한다.",
      answer: true,
      explanation: "미아는 안내센터에서 보호하며 방송(#108)을 통해 보호자를 신속히 찾아야 합니다.",
    },
  ],
};

export const EMERGENCY_CONTACTS = [
  { role: "운영본부", number: "#100", color: "text-amber-400" },
  { role: "경비팀", number: "#101", color: "text-red-400" },
  { role: "보안팀", number: "#102", color: "text-red-400" },
  { role: "시설팀", number: "#103", color: "text-blue-400" },
  { role: "운영팀", number: "#104", color: "text-green-400" },
  { role: "입장통제팀", number: "#105", color: "text-orange-400" },
  { role: "의료팀", number: "#106", color: "text-pink-400" },
  { role: "기술팀", number: "#107", color: "text-purple-400" },
  { role: "방송팀", number: "#108", color: "text-cyan-400" },
];

export const TIMELINE_EVENTS: TimelineEvent[] = [
  { time: "07:00", title: "스태프 집결·브리핑", description: "전체 스태프 집결, 역할별 최종 브리핑 진행", type: "setup" },
  { time: "08:00", title: "구역 점검 및 셋업", description: "각 구역별 시설·장비 최종 점검 및 셋업", type: "setup" },
  { time: "09:00", title: "행사장 오픈", description: "게이트 개방, 관람객 입장 시작", type: "open" },
  { time: "11:00", title: "오전 마켓 오픈", description: "마켓·팝업 구역 정식 운영 시작", type: "event" },
  { time: "13:00", title: "점심 피크타임", description: "F&B 구역 최대 혼잡 예상, 추가 인력 배치", type: "event" },
  { time: "15:00", title: "메인 공연 1부", description: "메인스테이지 공연 시작, 무대 스태프 전원 대기", type: "event" },
  { time: "17:00", title: "교대 스케줄 1차", description: "오후 교대 스태프 배치 전환", type: "setup" },
  { time: "18:00", title: "메인 공연 2부", description: "메인 공연 2부 시작, 가장 많은 관람객 예상", type: "event" },
  { time: "20:00", title: "피날레 공연", description: "피날레 공연 및 클로징 세레모니", type: "event" },
  { time: "21:00", title: "관람객 퇴장 유도", description: "순차적 퇴장 유도, 분실물 확인", type: "close" },
  { time: "22:00", title: "행사 종료·정리", description: "전체 구역 정리 및 스태프 해산", type: "close" },
];

/* ──────────────────────────────────────────────────────────
   ZONES — 포트빌리지 부산 2026 (최종 구조)
   id 네이밍: 역할 접두사 + 도면 순서 번호
     F  = FOOD존        M  = 플리마켓존     C  = 체험/콘텐츠
     P  = 팝업존         FA = 편의시설       E  = 출입구
   번호는 도면 순서(실내 1행→2행→파도비우소→FOOD부스줄→야외본문) 그대로.
   ────────────────────────────────────────────────────────── */
export const ZONES = [
  // 실내 1행
  { id: "F1", name: "동문식당가", role: "fnb" as const, capacity: 600, color: "#2B7FD4" },
  { id: "C1", name: "수중광장(버블쇼)", role: "stage" as const, capacity: 1000, color: "#F08020" },
  { id: "F2", name: "서문식당가", role: "fnb" as const, capacity: 600, color: "#2B7FD4" },

  // 실내 2행
  { id: "M1", name: "동문시장", role: "market" as const, capacity: 400, color: "#2EB04B" },
  { id: "FA1", name: "의무실·주민자치센터", role: "facility" as const, capacity: 40, color: "#C040A0" },
  { id: "M2", name: "서문시장", role: "market" as const, capacity: 400, color: "#2EB04B" },

  // 파도비우소 (실내 박스 옆 독립 칸)
  { id: "FA2", name: "파도비우소 (화장실·수유실)", role: "facility" as const, capacity: 50, color: "#C040A0" },

  // FOOD 부스 + 출입구 줄 (야외 구역 안, 맨 위 가로줄, 좌→우)
  { id: "F3", name: "푸드트럭존", role: "fnb" as const, capacity: 100, color: "#2B7FD4" },
  { id: "FA3", name: "분리수거존(좌)", role: "facility" as const, capacity: 50, color: "#C040A0" },
  { id: "F4", name: "FOOD 부스 1", role: "fnb" as const, capacity: 200, color: "#2B7FD4" },
  { id: "E1", name: "출입구(좌)", role: "entrance" as const, capacity: 300, color: "#534AB7" },
  { id: "F5", name: "FOOD 부스 2", role: "fnb" as const, capacity: 200, color: "#2B7FD4" },
  { id: "F6", name: "FOOD 부스 3", role: "fnb" as const, capacity: 200, color: "#2B7FD4" },
  { id: "E2", name: "출입구(우)", role: "entrance" as const, capacity: 300, color: "#534AB7" },
  { id: "F7", name: "FOOD 부스 4", role: "fnb" as const, capacity: 200, color: "#2B7FD4" },
  { id: "FA4", name: "분리수거존(우)", role: "facility" as const, capacity: 50, color: "#C040A0" },

  // 야외 본문 (좌→우)
  { id: "P1", name: "BTS THE CITY ARIRANG BUSAN", role: "popup" as const, capacity: 300, color: "#F5D400" },
  { id: "C2", name: "파도놀이터 (휴게 공간)", role: "stage" as const, capacity: 300, color: "#9aa0a8" },
  { id: "FA5", name: "항구마을 우물(실외)", role: "facility" as const, capacity: 50, color: "#9aa0a8" },
  { id: "M3", name: "파도마당 (휴게 공간)", role: "market" as const, capacity: 500, color: "#9aa0a8" },
  { id: "F8", name: "부산고메셀렉션", role: "fnb" as const, capacity: 250, color: "#2B7FD4" },
  { id: "C3", name: "포트게더링", role: "stage" as const, capacity: 400, color: "#F08020" },
  { id: "E3", name: "입구", role: "entrance" as const, capacity: 800, color: "#534AB7" },
];

export const FALLBACK_STAFF: Staff[] = [
  { id: "1", name: "김민준", phone: "010-1234-5678", role: "entrance", zone: "입구", shift_start: "07:00", shift_end: "15:00", is_trained: true, quiz_score: 6, quiz_completed_at: new Date().toISOString(), created_at: new Date().toISOString() },
  { id: "2", name: "이서연", phone: "010-2345-6789", role: "entrance", zone: "입구", shift_start: "07:00", shift_end: "15:00", is_trained: true, quiz_score: 7, quiz_completed_at: new Date().toISOString(), created_at: new Date().toISOString() },
  { id: "3", name: "박지훈", phone: "010-3456-7890", role: "entrance", zone: "출입구(좌)", shift_start: "15:00", shift_end: "22:00", is_trained: false, quiz_score: null, quiz_completed_at: null, created_at: new Date().toISOString() },
  { id: "4", name: "최유진", phone: "010-4567-8901", role: "fnb", zone: "동문식당가", shift_start: "08:00", shift_end: "16:00", is_trained: true, quiz_score: 5, quiz_completed_at: new Date().toISOString(), created_at: new Date().toISOString() },
  { id: "5", name: "정다은", phone: "010-5678-9012", role: "fnb", zone: "서문식당가", shift_start: "08:00", shift_end: "16:00", is_trained: true, quiz_score: 7, quiz_completed_at: new Date().toISOString(), created_at: new Date().toISOString() },
  { id: "6", name: "한승우", phone: "010-6789-0123", role: "fnb", zone: "FOOD 부스 1", shift_start: "16:00", shift_end: "22:00", is_trained: false, quiz_score: null, quiz_completed_at: null, created_at: new Date().toISOString() },
  { id: "7", name: "오수빈", phone: "010-7890-1234", role: "market", zone: "동문시장", shift_start: "09:00", shift_end: "18:00", is_trained: true, quiz_score: 6, quiz_completed_at: new Date().toISOString(), created_at: new Date().toISOString() },
  { id: "8", name: "임재현", phone: "010-8901-2345", role: "market", zone: "서문시장", shift_start: "09:00", shift_end: "18:00", is_trained: false, quiz_score: null, quiz_completed_at: null, created_at: new Date().toISOString() },
  { id: "9", name: "신혜린", phone: "010-9012-3456", role: "popup", zone: "BTS THE CITY ARIRANG BUSAN", shift_start: "10:00", shift_end: "20:00", is_trained: true, quiz_score: 7, quiz_completed_at: new Date().toISOString(), created_at: new Date().toISOString() },
  { id: "10", name: "강태양", phone: "010-0123-4567", role: "popup", zone: "BTS THE CITY ARIRANG BUSAN", shift_start: "10:00", shift_end: "20:00", is_trained: true, quiz_score: 5, quiz_completed_at: new Date().toISOString(), created_at: new Date().toISOString() },
  { id: "11", name: "윤채원", phone: "010-1234-0987", role: "stage", zone: "수중광장(버블쇼)", shift_start: "07:00", shift_end: "22:00", is_trained: true, quiz_score: 6, quiz_completed_at: new Date().toISOString(), created_at: new Date().toISOString() },
  { id: "12", name: "류동현", phone: "010-2345-1098", role: "stage", zone: "포트게더링", shift_start: "07:00", shift_end: "22:00", is_trained: false, quiz_score: null, quiz_completed_at: null, created_at: new Date().toISOString() },
  { id: "13", name: "백소영", phone: "010-3456-2109", role: "facility", zone: "의무실·주민자치센터", shift_start: "08:00", shift_end: "22:00", is_trained: true, quiz_score: 7, quiz_completed_at: new Date().toISOString(), created_at: new Date().toISOString() },
  { id: "14", name: "송민호", phone: "010-4567-3210", role: "facility", zone: "파도비우소 (화장실·수유실)", shift_start: "08:00", shift_end: "22:00", is_trained: false, quiz_score: null, quiz_completed_at: null, created_at: new Date().toISOString() },
  { id: "15", name: "정준호", phone: "010-5678-4321", role: "entrance", zone: "출입구(우)", shift_start: "07:00", shift_end: "15:00", is_trained: true, quiz_score: 6, quiz_completed_at: new Date().toISOString(), created_at: new Date().toISOString() },
  { id: "16", name: "이민석", phone: "010-6789-5432", role: "entrance", zone: "입구", shift_start: "15:00", shift_end: "22:00", is_trained: true, quiz_score: 5, quiz_completed_at: new Date().toISOString(), created_at: new Date().toISOString() },
  { id: "17", name: "박현준", phone: "010-7890-6543", role: "fnb", zone: "푸드코트존", shift_start: "08:00", shift_end: "16:00", is_trained: false, quiz_score: null, quiz_completed_at: null, created_at: new Date().toISOString() },
  { id: "18", name: "최지은", phone: "010-8901-7654", role: "fnb", zone: "푸드코트존", shift_start: "16:00", shift_end: "22:00", is_trained: true, quiz_score: 6, quiz_completed_at: new Date().toISOString(), created_at: new Date().toISOString() },
  { id: "19", name: "정수빈", phone: "010-9012-8765", role: "fnb", zone: "FOOD 부스 2", shift_start: "08:00", shift_end: "16:00", is_trained: true, quiz_score: 7, quiz_completed_at: new Date().toISOString(), created_at: new Date().toISOString() },
  { id: "20", name: "한준영", phone: "010-0123-9876", role: "fnb", zone: "FOOD 부스 2", shift_start: "16:00", shift_end: "22:00", is_trained: false, quiz_score: null, quiz_completed_at: null, created_at: new Date().toISOString() },
  { id: "21", name: "오지훈", phone: "010-1234-1111", role: "fnb", zone: "FOOD 부스 3", shift_start: "08:00", shift_end: "16:00", is_trained: true, quiz_score: 5, quiz_completed_at: new Date().toISOString(), created_at: new Date().toISOString() },
  { id: "22", name: "임현지", phone: "010-2345-2222", role: "fnb", zone: "FOOD 부스 3", shift_start: "16:00", shift_end: "22:00", is_trained: true, quiz_score: 6, quiz_completed_at: new Date().toISOString(), created_at: new Date().toISOString() },
  { id: "23", name: "신재혁", phone: "010-3456-3333", role: "fnb", zone: "FOOD 부스 4", shift_start: "08:00", shift_end: "16:00", is_trained: false, quiz_score: null, quiz_completed_at: null, created_at: new Date().toISOString() },
  { id: "24", name: "강민준", phone: "010-4567-4444", role: "fnb", zone: "FOOD 부스 4", shift_start: "16:00", shift_end: "22:00", is_trained: true, quiz_score: 7, quiz_completed_at: new Date().toISOString(), created_at: new Date().toISOString() },
  { id: "25", name: "윤서진", phone: "010-5678-5555", role: "fnb", zone: "부산고메셀렉션", shift_start: "08:00", shift_end: "16:00", is_trained: true, quiz_score: 6, quiz_completed_at: new Date().toISOString(), created_at: new Date().toISOString() },
  { id: "26", name: "류지우", phone: "010-6789-6666", role: "fnb", zone: "부산고메셀렉션", shift_start: "16:00", shift_end: "22:00", is_trained: true, quiz_score: 5, quiz_completed_at: new Date().toISOString(), created_at: new Date().toISOString() },
  { id: "27", name: "백준호", phone: "010-7890-7777", role: "market", zone: "파도마당 (휴게 공간)", shift_start: "09:00", shift_end: "18:00", is_trained: false, quiz_score: null, quiz_completed_at: null, created_at: new Date().toISOString() },
  { id: "28", name: "송혜빈", phone: "010-8901-8888", role: "market", zone: "파도마당 (휴게 공간)", shift_start: "09:00", shift_end: "18:00", is_trained: true, quiz_score: 6, quiz_completed_at: new Date().toISOString(), created_at: new Date().toISOString() },
  { id: "29", name: "김태호", phone: "010-9012-9999", role: "market", zone: "파도마당 (휴게 공간)", shift_start: "09:00", shift_end: "18:00", is_trained: true, quiz_score: 7, quiz_completed_at: new Date().toISOString(), created_at: new Date().toISOString() },
  { id: "30", name: "이준영", phone: "010-0123-1010", role: "popup", zone: "BTS THE CITY ARIRANG BUSAN", shift_start: "10:00", shift_end: "20:00", is_trained: true, quiz_score: 5, quiz_completed_at: new Date().toISOString(), created_at: new Date().toISOString() },
  { id: "31", name: "박수현", phone: "010-1234-1111", role: "popup", zone: "BTS THE CITY ARIRANG BUSAN", shift_start: "10:00", shift_end: "20:00", is_trained: false, quiz_score: null, quiz_completed_at: null, created_at: new Date().toISOString() },
  { id: "32", name: "최영준", phone: "010-2345-1212", role: "stage", zone: "파도놀이터 (휴게 공간)", shift_start: "07:00", shift_end: "22:00", is_trained: true, quiz_score: 6, quiz_completed_at: new Date().toISOString(), created_at: new Date().toISOString() },
  { id: "33", name: "정성훈", phone: "010-3456-1313", role: "stage", zone: "파도놀이터 (휴게 공간)", shift_start: "07:00", shift_end: "22:00", is_trained: true, quiz_score: 5, quiz_completed_at: new Date().toISOString(), created_at: new Date().toISOString() },
  { id: "34", name: "한지호", phone: "010-4567-1414", role: "stage", zone: "포트게더링", shift_start: "07:00", shift_end: "22:00", is_trained: false, quiz_score: null, quiz_completed_at: null, created_at: new Date().toISOString() },
  { id: "35", name: "오연주", phone: "010-5678-1515", role: "facility", zone: "분리수거존(좌)", shift_start: "08:00", shift_end: "22:00", is_trained: true, quiz_score: 6, quiz_completed_at: new Date().toISOString(), created_at: new Date().toISOString() },
  { id: "36", name: "임성준", phone: "010-6789-1616", role: "facility", zone: "분리수거존(좌)", shift_start: "08:00", shift_end: "22:00", is_trained: true, quiz_score: 7, quiz_completed_at: new Date().toISOString(), created_at: new Date().toISOString() },
  { id: "37", name: "신민경", phone: "010-7890-1717", role: "facility", zone: "분리수거존(우)", shift_start: "08:00", shift_end: "22:00", is_trained: false, quiz_score: null, quiz_completed_at: null, created_at: new Date().toISOString() },
  { id: "38", name: "강지현", phone: "010-8901-1818", role: "facility", zone: "분리수거존(우)", shift_start: "08:00", shift_end: "22:00", is_trained: true, quiz_score: 5, quiz_completed_at: new Date().toISOString(), created_at: new Date().toISOString() },
  { id: "39", name: "윤지훈", phone: "010-9012-1919", role: "facility", zone: "항구마을 우물(실외)", shift_start: "08:00", shift_end: "22:00", is_trained: true, quiz_score: 6, quiz_completed_at: new Date().toISOString(), created_at: new Date().toISOString() },
  { id: "40", name: "류현지", phone: "010-0123-2020", role: "facility", zone: "항구마을 우물(실외)", shift_start: "08:00", shift_end: "22:00", is_trained: true, quiz_score: 7, quiz_completed_at: new Date().toISOString(), created_at: new Date().toISOString() },
  { id: "41", name: "한주호", phone: "010-6666-7070", role: "entrance", zone: "입구", shift_start: "15:00", shift_end: "22:00", is_trained: true, quiz_score: 5, quiz_completed_at: new Date().toISOString(), created_at: new Date().toISOString() },
  { id: "42", name: "오소은", phone: "010-7777-8080", role: "entrance", zone: "출입구(좌)", shift_start: "07:00", shift_end: "15:00", is_trained: false, quiz_score: null, quiz_completed_at: null, created_at: new Date().toISOString() },
  { id: "43", name: "임영석", phone: "010-8888-9090", role: "entrance", zone: "입구", shift_start: "15:00", shift_end: "22:00", is_trained: true, quiz_score: 6, quiz_completed_at: new Date().toISOString(), created_at: new Date().toISOString() },
  { id: "44", name: "김태희", phone: "010-1111-2020", role: "fnb", zone: "FOOD 부스 2", shift_start: "08:00", shift_end: "16:00", is_trained: true, quiz_score: 6, quiz_completed_at: new Date().toISOString(), created_at: new Date().toISOString() },
  { id: "45", name: "이준혁", phone: "010-2222-3030", role: "fnb", zone: "동문식당가", shift_start: "16:00", shift_end: "22:00", is_trained: true, quiz_score: 5, quiz_completed_at: new Date().toISOString(), created_at: new Date().toISOString() },
  { id: "46", name: "박민수", phone: "010-3333-4040", role: "fnb", zone: "FOOD 부스 1", shift_start: "16:00", shift_end: "22:00", is_trained: false, quiz_score: null, quiz_completed_at: null, created_at: new Date().toISOString() },
  { id: "47", name: "최예진", phone: "010-4444-5050", role: "fnb", zone: "서문식당가", shift_start: "08:00", shift_end: "16:00", is_trained: true, quiz_score: 7, quiz_completed_at: new Date().toISOString(), created_at: new Date().toISOString() },
  { id: "48", name: "정준호", phone: "010-5555-6060", role: "fnb", zone: "FOOD 부스 2", shift_start: "08:00", shift_end: "16:00", is_trained: true, quiz_score: 6, quiz_completed_at: new Date().toISOString(), created_at: new Date().toISOString() },
  { id: "49", name: "신태호", phone: "010-9999-1010", role: "facility", zone: "의무실·주민자치센터", shift_start: "08:00", shift_end: "22:00", is_trained: true, quiz_score: 5, quiz_completed_at: new Date().toISOString(), created_at: new Date().toISOString() },
  { id: "50", name: "강혜민", phone: "010-0000-1111", role: "facility", zone: "파도비우소 (화장실·수유실)", shift_start: "08:00", shift_end: "22:00", is_trained: true, quiz_score: 7, quiz_completed_at: new Date().toISOString(), created_at: new Date().toISOString() }
];